name: Auto-merge dependabot flake updates

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  dependabot:
    name: Enable Dependabot auto-merge
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write # needed to enable auto-merge on matching Dependabot pull requests
      contents: write # needed by GitHub CLI to set auto-merge for the pull request

    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3

      - name: Enable auto-merge for nix flake updates
        if: ${{steps.dependabot-metadata.outputs.package-ecosystem == 'nix'}}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
