name: Nix flake check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  nix-flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # needed for determinate nix installer (flakehub OIDC token)

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@7c4cc317e802185875512bfcb68259257279d767 # v3
        with:
          diagnostic-endpoint: ""
          extra-conf: |
            extra-experimental-features = ca-derivations provenance wasm-builtin
            extra-substituters = https://nix-community.cachix.org https://devenv.cachix.org https://helix.cachix.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= helix.cachix.org-1:ejp9KQpR1FBI2onstMQ34yogDm4OgU2ru6lIwPvuCVs=
            sandbox = relaxed

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # main
        with:
          diagnostic-endpoint: ""
          use-flakehub: false

      - name: Run nix flake check
        run: nix flake check -L

      - name: Fix hash mismatches
        if: failure() && github.event_name == 'pull_request'
        id: fix-hashes
        env:
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |-
          git stash --include-untracked
          git fetch --depth=1 origin "$GITHUB_HEAD_REF"
          git checkout -B "$GITHUB_HEAD_REF" "$PR_HEAD_SHA"

          determinate-nixd fix hashes --auto-apply

          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add --update --ignore-removal .
            git commit -m "[dependabot skip] Automatically fix Nix hashes"
            git push origin "$GITHUB_HEAD_REF"
          fi

          git checkout -
          git stash pop || true
